/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PanierMystere } from "./PanierMystere";
import { PanierMystereCountArgs } from "./PanierMystereCountArgs";
import { PanierMystereFindManyArgs } from "./PanierMystereFindManyArgs";
import { PanierMystereFindUniqueArgs } from "./PanierMystereFindUniqueArgs";
import { DeletePanierMystereArgs } from "./DeletePanierMystereArgs";
import { PanierMystereService } from "../panierMystere.service";
@graphql.Resolver(() => PanierMystere)
export class PanierMystereResolverBase {
  constructor(protected readonly service: PanierMystereService) {}

  async _panierMysteresMeta(
    @graphql.Args() args: PanierMystereCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PanierMystere])
  async panierMysteres(
    @graphql.Args() args: PanierMystereFindManyArgs
  ): Promise<PanierMystere[]> {
    return this.service.panierMysteres(args);
  }

  @graphql.Query(() => PanierMystere, { nullable: true })
  async panierMystere(
    @graphql.Args() args: PanierMystereFindUniqueArgs
  ): Promise<PanierMystere | null> {
    const result = await this.service.panierMystere(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PanierMystere)
  async deletePanierMystere(
    @graphql.Args() args: DeletePanierMystereArgs
  ): Promise<PanierMystere | null> {
    try {
      return await this.service.deletePanierMystere(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
