/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PanierMystereService } from "../panierMystere.service";
import { PanierMystereCreateInput } from "./PanierMystereCreateInput";
import { PanierMystere } from "./PanierMystere";
import { PanierMystereFindManyArgs } from "./PanierMystereFindManyArgs";
import { PanierMystereWhereUniqueInput } from "./PanierMystereWhereUniqueInput";
import { PanierMystereUpdateInput } from "./PanierMystereUpdateInput";

export class PanierMystereControllerBase {
  constructor(protected readonly service: PanierMystereService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PanierMystere })
  async createPanierMystere(
    @common.Body() data: PanierMystereCreateInput
  ): Promise<PanierMystere> {
    return await this.service.createPanierMystere({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PanierMystere] })
  @ApiNestedQuery(PanierMystereFindManyArgs)
  async panierMysteres(
    @common.Req() request: Request
  ): Promise<PanierMystere[]> {
    const args = plainToClass(PanierMystereFindManyArgs, request.query);
    return this.service.panierMysteres({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PanierMystere })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async panierMystere(
    @common.Param() params: PanierMystereWhereUniqueInput
  ): Promise<PanierMystere | null> {
    const result = await this.service.panierMystere({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PanierMystere })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePanierMystere(
    @common.Param() params: PanierMystereWhereUniqueInput,
    @common.Body() data: PanierMystereUpdateInput
  ): Promise<PanierMystere | null> {
    try {
      return await this.service.updatePanierMystere({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PanierMystere })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePanierMystere(
    @common.Param() params: PanierMystereWhereUniqueInput
  ): Promise<PanierMystere | null> {
    try {
      return await this.service.deletePanierMystere({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
